### ISSUE TITLE
SipSwitch doesn't work on Android 5.0 Lollipop

### ISSUE THREAD

**Issue by robert7k** [robert7k/sipswitch#7]
Both buttons stopped working.

**Comment by BeeZerk** [comment]
Is there another solution for activate sip on lg g3 with android 5.0 (lollipop)?

**Comment by robert7k** [comment]
Google changed the SIP API with Android 5.0. I'm not sure yet if it's possible to get this widget to work on Android 5.0

**Comment by frankmorgner** [comment]
2dd80edd27e1219fe66c8dc2ee9acb4408ceeba8 works together with #10 on Android 5.1.1. I verified with Cyanogenmod 12.1

**Comment by frankmorgner** [comment]
What is the left button supposed to do (the one *without* the green bar). It still doesn't have any function for me. Where can I find the action it should trigger in the code?

**Comment by robert7k** [comment]
Thanks for the patch, I'll look at it later.

The left button opens the SIP settings menu. In Android 5.1 this would be Phone -> Menu -> Settings -> Calls -> Accounts.

**Comment by frankmorgner** [comment]
Opening the SIP settings menu fails with "permission denied":
```
07-11 23:28:54.610  12693-12693/eu.siebeck.sipswitch E/eu.siebeck.sipswitch.SipSwitchActivity﹕ Error starting intent
    java.lang.SecurityException: Permission Denial: starting Intent { act=android.intent.action.MAIN flg=0x10000000 cmp=com.android.phone/.settings.PhoneAccountSettingsActivity } from ProcessRecord{2642160a 12693:eu.siebeck.sipswitch/u0a94} (pid=12693, uid=10094) not exported from uid 1001
            at android.os.Parcel.readException(Parcel.java:1546)
            at android.os.Parcel.readException(Parcel.java:1499)
            at android.app.ActivityManagerProxy.startActivity(ActivityManagerNative.java:2449)
            at android.app.Instrumentation.execStartActivity(Instrumentation.java:1496)
            at android.app.ContextImpl.startActivity(ContextImpl.java:1276)
            at android.app.ContextImpl.startActivity(ContextImpl.java:1258)
            at android.content.ContextWrapper.startActivity(ContextWrapper.java:329)
            at android.content.ContextWrapper.startActivity(ContextWrapper.java:329)
            at eu.siebeck.sipswitch.SipSwitchActivity.onReceive(SipSwitchActivity.java:103)
            at android.app.ActivityThread.handleReceiver(ActivityThread.java:2640)
            at android.app.ActivityThread.access$1800(ActivityThread.java:154)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1398)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5289)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
```
The problem seems to be that `PhoneAccountSettingsActivity` misses the flag `android:exported="true"` in its manifest (see https://android.googlesource.com/platform/packages/services/Telephony/+/ce8ae2a%5E!/).

I think the best you could do is remove that button.

**Comment by frankmorgner** [comment]
I have https://github.com/frankmorgner/sipswitch/commit/c5035d45a53f70e04e649db708a819e117158706 and https://github.com/frankmorgner/sipswitch/commit/d2de02cda8c63e0783f7ff6ac99b4cc04ae10cd7 which make the widget fully functional again. I'm waiting for a fix for the broken configuration in https://github.com/robert7k/sipswitch/commit/3baa3d829c4b812e49ad18671aec8159a3b62fe2 for a pull request.

**Comment by robert7k** [comment]
I have merged your fixes. They also work with Android 5.0, so I've adjusted that. Thanks.
